### ISSUE TITLE
incompatibility with libpng v1.6?

### ISSUE THREAD

**Issue by blun** [mozilla/mozjpeg#216]
Somebody please confirm whether compiling v3.1 with png support works with libpng version 1.6.
It's giving me the
`"Unrecognized input file format --- perhaps you need -targa"`
here although i seem to have installed all possible build dependencies and stuff and can't think of anything else i'm missing here. It's late at night and the problem may yet be between screen and chair, though.

configure script is
`"checking for libpng... yes"`
fine.
I've got nasm (v2.12.01), pkg-config (v0.29), automake (v1.15), autoconf (v2.69), libtool (v2.4.6), libpng (v1.6.23), and libpng-dev installed.
configure and make run smoothly and produced working binaries - except for the missing png support. Compiled with gcc v5.4.0.

`checking pkg-config is at least version 0.9.0... yes`
`checking if libtool supports shared libraries... yes`
`checking whether the assembler (nasm -felf -DELF) works... yes`

**Comment by blun** [comment]
As i just discovered, it seems to work fine with static compiles.

**Comment by pornel** [comment]
I'm surprised that you didn't get compilation error or a crash, because if it detects libpng in configure, it should build with it and then use it unconditionally.

In general it's compatible with libjpeg 1.6 API.

**Comment by blun** [comment]
(Default build procedure produces static builds anyway, doesn't it?.. Thought i've seen dynamic linking with binaries produced in an earlier try yesterday, though...)
Now i fail trying to reproduce the problem myself. I hope it's a good thing, hopefully just some oddity because maybe last night i tried to use my compiler before it was fully installed or something..?
Maybe i'll try and experiment a little more in the hope of getting a better understanding of what happened - but for now it rather looks like:
Never mind, problem solved itself, close case. :-)
