### ISSUE TITLE
Undefined reference to `ceilf` in build on Linux x86_64

### ISSUE THREAD

**Issue by attilarepka** [mozilla/mozjpeg#445]
I did `git bisect` and it shows build fails from [this](https://github.com/mozilla/mozjpeg/commit/c6d33b6d69c06bc8ac8fe7379aed18255552dd70) commit.

CMake command:
`cmake -G"Unix Makefiles" -S . -B build && cd build && make -j$(nproc)`

CMake logs:
```
[ 90%] Building C object CMakeFiles/turbojpeg-static.dir/jdatadst-tj.c.o
/usr/bin/ld: libjpeg.a(jcdctmgr.c.o): in function `preprocess_deringing':
jcdctmgr.c:(.text+0x2be0): undefined reference to `ceilf'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/example-static.dir/build.make:98: example-static] Error 1
make[1]: *** [CMakeFiles/Makefile2:857: CMakeFiles/example-static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 90%] Building C object CMakeFiles/turbojpeg-static.dir/jdatasrc-tj.c.o
[ 90%] Linking C executable djpeg-static
[ 90%] Building C object CMakeFiles/turbojpeg-static.dir/rdbmp.c.o
[ 91%] Building C object CMakeFiles/turbojpeg-static.dir/rdppm.c.o
[ 91%] Built target djpeg-static
[ 91%] Building C object CMakeFiles/turbojpeg-static.dir/wrbmp.c.o
[ 91%] Building C object CMakeFiles/turbojpeg-static.dir/wrppm.c.o
[ 91%] Linking C shared library libturbojpeg.so
[ 91%] Built target turbojpeg
[ 92%] Linking C executable jpegtran-static
[ 92%] Built target jpegtran-static
[ 92%] Linking C static library libturbojpeg.a
[ 92%] Built target turbojpeg-static
[ 92%] Linking C shared library ../libjpeg.so
[ 92%] Built target jpeg
make: *** [Makefile:146: all] Error 2
```
